local map = vim.keymap.set
map("n", "o", "<Plug>(DBUI_SelectLine)", { buffer = 0, desc = "Select Line" })
map("n", "<CR>", "<Plug>(DBUI_SelectLine)", { buffer = 0, desc = "Select Line" })
map("n", "S", "<Plug>(DBUI_SelectLineVsplit)", { buffer = 0, desc = "Select Line Vsplit" })
map("n", "R", "<Plug>(DBUI_Redraw)", { buffer = 0, desc = "Redraw" })
map("n", "d", "<Plug>(DBUI_DeleteLine)", { buffer = 0, desc = "Delete Line" })
map("n", "A", "<Plug>(DBUI_AddConnection)", { buffer = 0, desc = "Add Connection" })
map("n", "H", "<Plug>(DBUI_ToggleDetails)", { buffer = 0, desc = "Toggle Details" })
map("n", "r", "<Plug>(DBUI_RenameLine)", { buffer = 0, desc = "Rename Line" })
map("n", "q", "<Plug>(DBUI_Quit)", { buffer = 0, desc = "Quit" })
-- map("n", "<c-k>", "<Plug>(DBUI_GotoFirstSibling)", { buffer = 0, desc = "Goto First Sibling" })
-- map("n", "<c-j>", "<Plug>(DBUI_GotoLastSibling)", { buffer = 0, desc = "Goto Last Sibling" })
-- map("n", "<C-p>", "<Plug>(DBUI_GotoParentNode)", { buffer = 0, desc = "Goto Parent Node" })
-- map("n", "<C-n>", "<Plug>(DBUI_GotoChildNode)", { buffer = 0, desc = "Goto Child Node" })
-- map("n", "K", "<Plug>(DBUI_GotoPrevSibling)", { buffer = 0, desc = "Goto Prev Sibling" })
-- map("n", "J", "<Plug>(DBUI_GotoNextSibling)", { buffer = 0, desc = "Goto Next Sibling" })
