#!/usr/bin/env bash

if [ -z "$1" ]; then
    INFO=$(acpi -b | head -n 1)
else
    INFO=$(acpi -b | grep "Battery $1:")
fi

if [ -z "$INFO" ]; then
    exit 0
fi


echo "$INFO" | cut -f2 -d':' | awk -F', ' '
    { perc = gsub(/%/, "", $2) }

    $1 ~ /Full/ {
        icon = "󱟢 "
    }

    $1 ~ /Not charging|Charging/ { 
        if ($2 < 10) {
            icon = "󰢟 "
        } else if ($2 < 20) {
            icon = "󰢜 "
        } else if ($2 < 40) {
            icon = "󰂆 "
        } else if ($2 < 60) {
            icon = "󰂈 "
        } else if ($2 < 80) {
            icon = "󰂉 "
        } else if ($2 < 90) {
            icon = "󰂊 "
        } else {
            icon = "󰂋 "
        }
    }

    $1 ~ /Discharging/ {
        if ($2 < 10) {
            color = "#FF0000"
            icon = "󰂃 "
        } else if ($2 < 20) {
            color = "#FF3333"
            icon = "󰁻 "
        } else if ($2 < 40) {
            color = "#FFFF33"
            icon = "󰁽 "
        } else if ($2 < 60) {
            icon = "󰁿 "
        } else if ($2 < 80) {
            icon = "󰂁 "
        } else if ($2 < 90) {
            icon = "󰂂 "
        } else {
            icon = "󰁹 "
        }
    }

    { 
      print icon " " $2 "%"
      print icon " " $2 "%"
      if (color) print color
    }
'
