#!/usr/bin/env bash

CONTROLLER=$(bluetoothctl list | grep "[default]" | awk '{ print $2 }')

if [ -z "$CONTROLLER" ]; then
    exit 0
fi

(bluetoothctl show $CONTROLLER | grep -q "Powered: yes") && powered=1 || powered=0

case $BLOCK_BUTTON in
  1)
    (($powered)) && turn_to=off || turn_to=on
    echo 
    echo 
    bluetoothctl power $turn_to &> /dev/null
    exit 0
  ;;
  3) blueman-manager ;;
esac

if (($powered)); then
  bluetoothctl info | awk '
      /Name:/ { name = $2 }
      /Connected:/ { connected = $2 }

      END {
          if (connected == "yes") {
              print "󰂱"
              print "󰂱"
              print "#6666DD"
          } else {
              print "󰂯"
              print "󰂯"
          }
      }
  '
else
  echo "󰂲"
  echo "󰂲"
fi
