#!/usr/bin/env bash

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

echo "Did you tested and check code standards? [y/N]"
read -n1 -s ans
if [[ ! $ans =~ [Yy] ]]; then
   exit 1
fi
