import = ["/home/alan/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "Caskaydia Cove Nerd Font"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Minus"
mods = "Control"

[selection]
save_to_clipboard = true

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "/bin/tmux"

[window]
dynamic_padding = true
