#!/usr/bin/env bash

path=$1

selected=$(eza -s accessed -r -D -1 $path | fzf)
if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
selected_path="$path$selected"
touch $selected_path

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected_path
fi

tmux switch-client -t $selected_name
